version: "2"

# Visit https://golangci-lint.run/ for usage documentation and information on
# other useful linters
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - paralleltest
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
  settings:
    paralleltest:
      # Terraform acceptance subtests all share a Coder instance, and cannot run
      # in parallel.
      ignore-missing-subtests: true

formatters:
  enable:
    - gofmt
